#!/bin/bash

version="v0.1.0"
usage="Usage: eclipse-signer /path/to/Eclipse.app"
err[1]="Invalid command"
err[2]="Invalid app container"

# Check for Eclipse folder parameter
if [[ -z "$@" ]]
then
  echo "${err[1]}"
  echo "${usage}"
  exit 1
elif [[ ! -d $1 ]]
then
  echo "${err[2]}"
  echo "${usage}"
  exit 1
fi

app=$1
read -p "Your Apple Developer ID (e.g. 3rd Party Mac Developer Application: Interactive Pioneers GmbH (XOPR4SD7S2)): " developerId

codesign --force --verify --verbose --sign "${developerId}" $app/Contents/MacOS/eclipse.ini
codesign --force --verify --verbose --sign "${developerId}" $app/Contents/MacOS/launcher
codesign --force --verify --verbose --sign "${developerId}" $app

# Verify app
if `codesign -v $app`
then
  echo "Eclipse signed successfully!"
else
  echo "Eclipse signing failed!"
fi
